### PR TITLE
Member Cards

### PR DESCRIPTION
**Pull request by Rohit-110**
Issue: #113 
image

### CODE REVIEW

**Comment by akshayw1** [comment]
Add the screenshot of the PR, or connect over VC on discord

**Comment by Rohit-110** [comment]
@akshayw1 added screenshot

**Comment by akshayw1** [comment]
@Rohit-110 Improve padding, and Make the design consistent

**Comment by Rohit-110** [comment]
@akshayw1 made the changes, update the screenshot

**Comment by Rohit-110** [comment]
@akshayw1  please review this pr

**Comment by Rohit-110** [comment]
@akshayw1 updated the sceenshot

**Pull request merged**
